trigger:
  - master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: ubuntu-latest

steps:
  - task: Cache@2
    inputs:
      key: '"yarn" | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: UsePulumi@0
    inputs:
      version: 'latest'
    displayName: 'Install Pulumi'

  # This task will login into azure cli
  - task: AzureCLI@2
    inputs:
      # This subscription should have access to the target azure resource group
      azureSubscription: 'hashnode-cover'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        pulumi login
        yarn install --frozen-lockfile --prefer-offline
        yarn run deploy
