trigger:
  - master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: ubuntu-latest

steps:
  - task: Cache@2
    inputs:
      key: '"yarn" | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: 'Cache yarn packages'

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: UsePulumi@0
    inputs:
      version: 'latest'
    displayName: 'Install Pulumi'

  - script: yarn install --frozen-lockfile --prefer-offline
    displayName: 'Install node_modules'

  # This task will log into azure cli and run inlineScript
  - task: AzureCLI@2
    inputs:
      # This subscription should have access to the target azure resource group
      azureSubscription: 'hashnode-cover'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      # PULUMI_ACCESS_TOKEN is a secret, so the only way to pass it as an env variable is using arguments
      arguments: '$(PULUMI_ACCESS_TOKEN)'
      addSpnToEnvironment: true
      inlineScript: |
        export PULUMI_ACCESS_TOKEN=$1
        pulumi login
      # Pulumi only supports "az login" with a service principal
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_CLIENT_SECRET=$servicePrincipalKey
        export ARM_TENANT_ID=$tenantId
      # Sadly, this is the easiest way to get subscription id
        export ARM_SUBSCRIPTION_ID=$(az account list --query "[?isDefault].id | [0]" | tr -d '"')
        yarn run deploy
