trigger:
  - master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: ubuntu-latest

steps:
  - task: Cache@2
    inputs:
      key: '"yarn" | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: UsePulumi@0
    inputs:
      version: '3.20.0'
    displayName: 'Install Pulumi'

  - script: |
      pulumi login
      yarn install --frozen-lockfile --prefer-offline
      yarn run deploy
    displayName: 'Deploy'
    env:
      PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
